# Generated by Django 6.0 on 2026-01-20 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='average_duration',
            field=models.DurationField(null=True),
        ),
    ]
