# Generated by Django 6.0 on 2026-02-16 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_remove_booking_day_remove_booking_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.IntegerField(choices=[(1, 'принятый'), (2, 'откланен'), (3, 'завершен')], default=1),
        ),
    ]
